(ns se.lixi.adventofcode2021.core
  (:gen-class)
  )

(load "util")
(load "day1")
(load "day2")
(load "day3")
(load "day4")
(load "day5")
(load "day6")
(load "day7")
(load "day8")
(load "day9")
(load "day10")
(load "day11")
(load "day12")
(load "day13")
(load "day14")
(load "day15")
(load "day16")
(load "day17")
(load "day18")

(defn -main
  "Run advent-of-code 2021."
  [& _]
  ;(println (day1 "day1.txt"))
  ;(println (day2 "day2.txt"))
  ;(println (day3 "day3.txt"))
  ;(println (day4 "day4.txt"))
  ;(println (day5 "day5.txt"))
  ;(println (day6 "day6.txt"))
  ;(println (day7 "day7.txt"))
  ;(println (day8 "day8.txt"))
  ;(println (day9 "day9.txt"))
  ;(println (day10 "day10.txt"))
  ;(println (day11 "day11.txt"))
  ;(println (day12 "day12.txt"))
  ;(println (day13 "day13.txt"))
  ;(println (day14 "day14.txt"))
  ;(println (day15 "day15.txt"))
  ;(println (day16 "day16.txt"))
  ;(println (day17 "day17.txt"))
  (println (day18 "day18.txt"))
  )

